- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Create teamcity root folder on host
  file:
    path: "{{item.value.path}}"
    state: directory
    mode: 0777
  with_dict: "{{storage}}"

- name: Create agent config dir
  file:
    path: "{{storage.data.path}}/config"
    state: directory
    mode: 0777

#- name: Create k8s resources
#  kubernetes.core.k8s:
#    template:
#    - nameSpace.yml
#    - serviceAccount.yml
#    - pv.yml
#    - pvc.yml
#    - serverDeployment.yml
#    - agentDeployment.yml
#    - extService.yml
#    - intService.yml
#  with_dict: "{{storage}}"
#  become_user: "{{admin_user}}"

- name: Create namespace
  kubernetes.core.k8s:
    template:
    - nameSpace.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: Create serviceAccount
  kubernetes.core.k8s:
    template:
    - serviceAccount.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: Create pv
  kubernetes.core.k8s:
    template:
    - pv.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: Create pvc
  kubernetes.core.k8s:
    template:
    - pvc.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: server deployment
  kubernetes.core.k8s:
    template:
    - serverDeployment.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: Create agent deployment
  kubernetes.core.k8s:
    template:
    - agentDeployment.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: ext service
  kubernetes.core.k8s:
    template:
    - extService.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

- name: Create int service
  kubernetes.core.k8s:
    template:
    - intService.yml
  with_dict: "{{storage}}"
  become_user: "{{admin_user}}"

#- name: Transfer helm chart config values file
#  template:
#    src: values.yml
#    dest: "/tmp/teamcity_values.yml"
#    mode: 0644
#
#- name: Install teamcity helm chart
#  kubernetes.core.helm:
#    release_name: "{{teamcity_app_name}}"
#    chart_ref: teamcity
#    chart_repo_url: https://codaglobal.github.io/coda-charts
#    release_namespace: "{{teamcity_namespace}}"
#    create_namespace: true
#    wait: no
#    values_files:
#      - /tmp/teamcity_values.yml
#  become_user: "{{admin_user}}"

#- name: Configure teamcity nodeport service
#  kubernetes.core.k8s:
#    namespace: "{{teamcity_namespace}}"
#    state: present
#    template: service.yml
#  become_user: "{{admin_user}}"
