apiVersion: v1
kind: Service
metadata:
  name: teamcity
  namespace: {{teamcity_namespace}}
  labels:
    app.kubernetes.io/instance=teamcity
    app.kubernetes.io/name=teamcity  
spec:
  type: NodePort
  ports:
  - port: {{teamcity_port}}
    targetPort: {{teamcity_port}}
    nodePort: {{teamcity_service_port}}
  selector:
    app.kubernetes.io/instance: teamcity
    app.kubernetes.io/name: teamcity
  sessionAffinity: None
