apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-{{item.key}}-pvc
  namespace: {{teamcity_namespace}}
spec:
  storageClassName: {{storage_class_name}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{item.value.size}}
