# REf: https://github.com/codaglobal/teamcity_helm/blob/main/values.yaml
agentReplicaCount: 1

image:
  tag: 2022.10-linux-sudo

pvc:
  data: teamcity-data-pvc
  logs: teamcity-logs-pvc
  config: teamcity-config-pvc

service:
  int_type: ClusterIP
  ext_type: NodePort
  port: {{teamcity_port}}
